'use client'

import { useState, useCallback } from 'react'
import { 
  FileText, 
  Download, 
  Copy, 
  Check, 
  BookOpen,
  Sparkles,
  X,
  Printer
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface StudySheetProps {
  worksheetContent: string
  chatHistory: { role: 'user' | 'assistant'; content: string }[]
  onClose: () => void
}

export function StudySheet({ worksheetContent, chatHistory, onClose }: StudySheetProps) {
  const [copied, setCopied] = useState(false)

  // Extract key insights from chat history
  const extractedInsights = chatHistory
    .filter(msg => msg.role === 'assistant')
    .map(msg => msg.content)
    .join('\n\n---\n\n')

  // Generate the study sheet content
  const generateStudySheetContent = useCallback(() => {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    })

    return `# Study Sheet
Generated on ${date}

---

## Original Material

${worksheetContent}

---

## AI-Generated Insights & Explanations

${extractedInsights || 'No conversations yet. Chat with Lumina to generate insights!'}

---

*Generated by Lumina - Your AI Learning Assistant*`
  }, [worksheetContent, extractedInsights])

  const handleCopy = useCallback(async () => {
    const content = generateStudySheetContent()
    await navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [generateStudySheetContent])

  const handleDownload = useCallback(() => {
    const content = generateStudySheetContent()
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `study-sheet-${new Date().toISOString().split('T')[0]}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [generateStudySheetContent])

  const handlePrint = useCallback(() => {
    window.print()
  }, [])

  const hasContent = worksheetContent || extractedInsights

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-ink/60 backdrop-blur-sm">
      <div className="w-full max-w-4xl max-h-[90vh] bg-background rounded-lg border border-border elevation-mockup flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-8 py-5 border-b border-border bg-cream">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-lg bg-primary flex items-center justify-center">
              <FileText className="w-6 h-6 text-primary-foreground" />
            </div>
            <div>
              <h2 className="text-xl font-serif font-semibold text-foreground">Study Sheet</h2>
              <p className="text-sm text-slate">Your learning summary</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="rounded-md border-border hover:bg-cream-soft hover:border-beige-deep transition-editorial"
            >
              {copied ? (
                <Check className="w-4 h-4 mr-1.5 text-green-600" />
              ) : (
                <Copy className="w-4 h-4 mr-1.5" />
              )}
              {copied ? 'Copied!' : 'Copy'}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="rounded-md border-border hover:bg-cream-soft hover:border-beige-deep transition-editorial"
            >
              <Printer className="w-4 h-4 mr-1.5" />
              Print
            </Button>
            <Button
              size="sm"
              onClick={handleDownload}
              className="bg-primary hover:bg-primary-deep text-primary-foreground rounded-md transition-editorial"
            >
              <Download className="w-4 h-4 mr-1.5" />
              Download
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              className="text-slate hover:text-foreground hover:bg-cream-soft rounded-md ml-2 transition-editorial"
            >
              <X className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 print:p-10 bg-background">
          {!hasContent ? (
            <div className="h-full flex flex-col items-center justify-center text-center py-16">
              <div className="w-20 h-20 rounded-xl bg-cream border border-beige-deep flex items-center justify-center mb-8">
                <BookOpen className="w-10 h-10 text-slate" />
              </div>
              <h3 className="text-2xl font-serif font-semibold text-foreground mb-3">
                No content yet
              </h3>
              <p className="text-slate text-base max-w-sm leading-relaxed">
                Add study material and chat with Lumina to generate your personalized study sheet.
              </p>
            </div>
          ) : (
            <div className="space-y-10">
              {/* Original Material Section */}
              {worksheetContent && (
                <section>
                  <div className="flex items-center gap-3 mb-5">
                    <BookOpen className="w-6 h-6 text-primary" />
                    <h3 className="text-2xl font-serif font-semibold text-foreground" style={{ letterSpacing: '-0.5px' }}>
                      Original Material
                    </h3>
                  </div>
                  <div className="bg-cream rounded-lg p-6 border border-beige-deep">
                    <StudySheetMarkdown content={worksheetContent} />
                  </div>
                </section>
              )}

              {/* AI Insights Section */}
              {extractedInsights && (
                <section>
                  <div className="flex items-center gap-3 mb-5">
                    <Sparkles className="w-6 h-6 text-primary" />
                    <h3 className="text-2xl font-serif font-semibold text-foreground" style={{ letterSpacing: '-0.5px' }}>
                      AI-Generated Insights
                    </h3>
                  </div>
                  <div className="space-y-5">
                    {chatHistory
                      .filter(msg => msg.role === 'assistant')
                      .map((msg, index) => (
                        <div 
                          key={index} 
                          className="bg-cream rounded-lg p-6 border border-beige-deep"
                        >
                          <StudySheetMarkdown content={msg.content} />
                        </div>
                      ))}
                  </div>
                </section>
              )}

              {/* Footer */}
              <footer className="pt-8 border-t border-border text-center">
                <p className="text-sm text-slate">
                  Generated by <span className="text-primary font-medium">Lumina</span> - Your AI Learning Assistant
                </p>
                <p className="text-xs text-stone mt-2">
                  {new Date().toLocaleDateString('en-US', { 
                    year: 'numeric', 
                    month: 'long', 
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit'
                  })}
                </p>
              </footer>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// Markdown renderer for study sheet
function StudySheetMarkdown({ content }: { content: string }) {
  const lines = content.split('\n')
  const elements: React.ReactNode[] = []

  const processInlineFormatting = (text: string): React.ReactNode => {
    const parts: React.ReactNode[] = []
    let remaining = text
    let key = 0

    while (remaining.length > 0) {
      const boldMatch = remaining.match(/\*\*(.+?)\*\*/)
      const codeMatch = remaining.match(/`([^`]+)`/)
      
      const matches = [
        boldMatch ? { match: boldMatch, type: 'bold' } : null,
        codeMatch ? { match: codeMatch, type: 'code' } : null,
      ].filter(Boolean).sort((a, b) => 
        (a?.match?.index ?? Infinity) - (b?.match?.index ?? Infinity)
      )

      if (matches.length > 0 && matches[0]) {
        const { match, type } = matches[0]
        const index = match?.index ?? 0
        
        if (index > 0) {
          parts.push(<span key={key++}>{remaining.slice(0, index)}</span>)
        }
        
        if (type === 'bold' && match) {
          parts.push(<strong key={key++} className="font-semibold text-foreground">{match[1]}</strong>)
        } else if (type === 'code' && match) {
          parts.push(
            <code key={key++} className="px-1.5 py-0.5 rounded-md bg-surface-code text-on-dark font-mono text-sm">
              {match[1]}
            </code>
          )
        }
        
        remaining = remaining.slice(index + (match?.[0]?.length ?? 0))
      } else {
        parts.push(<span key={key++}>{remaining}</span>)
        break
      }
    }

    return parts.length > 0 ? parts : text
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    if (line.startsWith('# ')) {
      elements.push(
        <h2 key={i} className="text-2xl font-serif font-bold text-foreground mt-5 mb-4 first:mt-0" style={{ letterSpacing: '-0.5px' }}>
          {processInlineFormatting(line.slice(2))}
        </h2>
      )
    } else if (line.startsWith('## ')) {
      elements.push(
        <h3 key={i} className="text-xl font-serif font-semibold text-foreground mt-5 mb-3" style={{ letterSpacing: '-0.5px' }}>
          {processInlineFormatting(line.slice(3))}
        </h3>
      )
    } else if (line.startsWith('### ')) {
      elements.push(
        <h4 key={i} className="text-lg font-semibold text-foreground mt-4 mb-2">
          {processInlineFormatting(line.slice(4))}
        </h4>
      )
    } else if (line.startsWith('> ')) {
      elements.push(
        <blockquote key={i} className="border-l-3 border-primary pl-5 my-4 text-charcoal italic" style={{ lineHeight: '1.55' }}>
          {processInlineFormatting(line.slice(2))}
        </blockquote>
      )
    } else if (line.match(/^[-*] /)) {
      elements.push(
        <li key={i} className="text-charcoal ml-6 my-1.5 list-disc text-base" style={{ lineHeight: '1.55' }}>
          {processInlineFormatting(line.slice(2))}
        </li>
      )
    } else if (line.match(/^\d+\. /)) {
      elements.push(
        <li key={i} className="text-charcoal ml-6 my-1.5 list-decimal text-base" style={{ lineHeight: '1.55' }}>
          {processInlineFormatting(line.replace(/^\d+\. /, ''))}
        </li>
      )
    } else if (line.trim() === '') {
      elements.push(<div key={i} className="h-3" />)
    } else if (line.trim() === '---') {
      elements.push(<hr key={i} className="my-5 border-border" />)
    } else {
      elements.push(
        <p key={i} className="text-charcoal text-base my-2" style={{ lineHeight: '1.55' }}>
          {processInlineFormatting(line)}
        </p>
      )
    }
  }

  return <div className="space-y-1">{elements}</div>
}
