'use client'

import { useState, useCallback } from 'react'
import { 
  FileText, 
  Download, 
  Copy, 
  Check, 
  BookOpen,
  Sparkles,
  X,
  Printer
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface StudySheetProps {
  worksheetContent: string
  chatHistory: { role: 'user' | 'assistant'; content: string }[]
  onClose: () => void
}

export function StudySheet({ worksheetContent, chatHistory, onClose }: StudySheetProps) {
  const [copied, setCopied] = useState(false)

  // Extract key insights from chat history
  const extractedInsights = chatHistory
    .filter(msg => msg.role === 'assistant')
    .map(msg => msg.content)
    .join('\n\n---\n\n')

  // Generate the study sheet content
  const generateStudySheetContent = useCallback(() => {
    const date = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    })

    return `# Study Sheet
Generated on ${date}

---

## Original Material

${worksheetContent}

---

## AI-Generated Insights & Explanations

${extractedInsights || 'No conversations yet. Chat with Lumina to generate insights!'}

---

*Generated by Lumina - Your AI Learning Assistant*`
  }, [worksheetContent, extractedInsights])

  const handleCopy = useCallback(async () => {
    const content = generateStudySheetContent()
    await navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [generateStudySheetContent])

  const handleDownload = useCallback(() => {
    const content = generateStudySheetContent()
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `study-sheet-${new Date().toISOString().split('T')[0]}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [generateStudySheetContent])

  const handlePrint = useCallback(() => {
    window.print()
  }, [])

  // Check if there's any content
  const hasContent = worksheetContent || extractedInsights

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm">
      <div className="w-full max-w-4xl max-h-[90vh] bg-card rounded-2xl border border-border/50 shadow-2xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-foreground">Study Sheet</h2>
              <p className="text-xs text-muted-foreground">Your learning summary</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="border-border/50 hover:bg-secondary/50"
            >
              {copied ? (
                <Check className="w-4 h-4 mr-1.5 text-green-500" />
              ) : (
                <Copy className="w-4 h-4 mr-1.5" />
              )}
              {copied ? 'Copied!' : 'Copy'}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="border-border/50 hover:bg-secondary/50"
            >
              <Printer className="w-4 h-4 mr-1.5" />
              Print
            </Button>
            <Button
              size="sm"
              onClick={handleDownload}
              className="bg-primary hover:bg-primary/90 text-primary-foreground"
            >
              <Download className="w-4 h-4 mr-1.5" />
              Download
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={onClose}
              className="text-muted-foreground hover:text-foreground ml-2"
            >
              <X className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 print:p-8">
          {!hasContent ? (
            <div className="h-full flex flex-col items-center justify-center text-center py-12">
              <div className="w-16 h-16 rounded-2xl bg-secondary/50 flex items-center justify-center mb-6">
                <BookOpen className="w-8 h-8 text-muted-foreground" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">
                No content yet
              </h3>
              <p className="text-muted-foreground text-sm max-w-sm">
                Add study material and chat with Lumina to generate your personalized study sheet.
              </p>
            </div>
          ) : (
            <div className="space-y-8">
              {/* Original Material Section */}
              {worksheetContent && (
                <section>
                  <div className="flex items-center gap-2 mb-4">
                    <BookOpen className="w-5 h-5 text-primary" />
                    <h3 className="text-lg font-semibold text-foreground font-serif">
                      Original Material
                    </h3>
                  </div>
                  <div className="bg-secondary/30 rounded-xl p-5 border border-border/30">
                    <StudySheetMarkdown content={worksheetContent} />
                  </div>
                </section>
              )}

              {/* AI Insights Section */}
              {extractedInsights && (
                <section>
                  <div className="flex items-center gap-2 mb-4">
                    <Sparkles className="w-5 h-5 text-accent" />
                    <h3 className="text-lg font-semibold text-foreground font-serif">
                      AI-Generated Insights
                    </h3>
                  </div>
                  <div className="space-y-4">
                    {chatHistory
                      .filter(msg => msg.role === 'assistant')
                      .map((msg, index) => (
                        <div 
                          key={index} 
                          className="bg-secondary/30 rounded-xl p-5 border border-border/30"
                        >
                          <StudySheetMarkdown content={msg.content} />
                        </div>
                      ))}
                  </div>
                </section>
              )}

              {/* Footer */}
              <footer className="pt-6 border-t border-border/30 text-center">
                <p className="text-xs text-muted-foreground">
                  Generated by <span className="text-primary font-medium">Lumina</span> - Your AI Learning Assistant
                </p>
                <p className="text-xs text-muted-foreground/60 mt-1">
                  {new Date().toLocaleDateString('en-US', { 
                    year: 'numeric', 
                    month: 'long', 
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit'
                  })}
                </p>
              </footer>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// Markdown renderer for study sheet (simplified version)
function StudySheetMarkdown({ content }: { content: string }) {
  const lines = content.split('\n')
  const elements: React.ReactNode[] = []

  const processInlineFormatting = (text: string): React.ReactNode => {
    const parts: React.ReactNode[] = []
    let remaining = text
    let key = 0

    while (remaining.length > 0) {
      const boldMatch = remaining.match(/\*\*(.+?)\*\*/)
      const codeMatch = remaining.match(/`([^`]+)`/)
      
      const matches = [
        boldMatch ? { match: boldMatch, type: 'bold' } : null,
        codeMatch ? { match: codeMatch, type: 'code' } : null,
      ].filter(Boolean).sort((a, b) => 
        (a?.match?.index ?? Infinity) - (b?.match?.index ?? Infinity)
      )

      if (matches.length > 0 && matches[0]) {
        const { match, type } = matches[0]
        const index = match?.index ?? 0
        
        if (index > 0) {
          parts.push(<span key={key++}>{remaining.slice(0, index)}</span>)
        }
        
        if (type === 'bold' && match) {
          parts.push(<strong key={key++} className="font-semibold text-foreground">{match[1]}</strong>)
        } else if (type === 'code' && match) {
          parts.push(
            <code key={key++} className="px-1.5 py-0.5 rounded bg-background/50 text-accent font-mono text-xs">
              {match[1]}
            </code>
          )
        }
        
        remaining = remaining.slice(index + (match?.[0]?.length ?? 0))
      } else {
        parts.push(<span key={key++}>{remaining}</span>)
        break
      }
    }

    return parts.length > 0 ? parts : text
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    if (line.startsWith('# ')) {
      elements.push(
        <h2 key={i} className="text-xl font-bold text-foreground mt-4 mb-3 first:mt-0 font-serif">
          {processInlineFormatting(line.slice(2))}
        </h2>
      )
    } else if (line.startsWith('## ')) {
      elements.push(
        <h3 key={i} className="text-lg font-semibold text-foreground mt-4 mb-2 font-serif">
          {processInlineFormatting(line.slice(3))}
        </h3>
      )
    } else if (line.startsWith('### ')) {
      elements.push(
        <h4 key={i} className="text-base font-semibold text-foreground mt-3 mb-2">
          {processInlineFormatting(line.slice(4))}
        </h4>
      )
    } else if (line.startsWith('> ')) {
      elements.push(
        <blockquote key={i} className="border-l-3 border-primary/50 pl-4 my-3 text-foreground/80 italic">
          {processInlineFormatting(line.slice(2))}
        </blockquote>
      )
    } else if (line.match(/^[-*] /)) {
      elements.push(
        <li key={i} className="text-foreground/80 ml-5 my-1 list-disc">
          {processInlineFormatting(line.slice(2))}
        </li>
      )
    } else if (line.match(/^\d+\. /)) {
      elements.push(
        <li key={i} className="text-foreground/80 ml-5 my-1 list-decimal">
          {processInlineFormatting(line.replace(/^\d+\. /, ''))}
        </li>
      )
    } else if (line.trim() === '') {
      elements.push(<div key={i} className="h-2" />)
    } else if (line.trim() === '---') {
      elements.push(<hr key={i} className="my-4 border-border/30" />)
    } else {
      elements.push(
        <p key={i} className="text-foreground/80 leading-relaxed my-2">
          {processInlineFormatting(line)}
        </p>
      )
    }
  }

  return <div className="space-y-1">{elements}</div>
}
